version: "3.9"

services:
  rabbitmq:
    container_name: fib_rabbitmq
    image: rabbitmq:management
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 30s
      timeout: 10s
      retries: 5

  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: fib_server
    volumes:
      - ./:/fibonacci
    command: >
      sh -c "./wait-for-it.sh rabbitmq:5672 -- sh ./entrypoint-server.sh"
    environment:
      - HOSTNAMERABBIT=rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq

  client:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: fib_client
    volumes:
      - ./:/fibonacci
    command: >
      sh -c "./wait-for-it.sh rabbitmq:5672 -- python3 ./rpc_client.py"
    depends_on:
      rabbitmq:
        condition: service_healthy
      server:
        condition: service_healthy
    links:
      - rabbitmq
